### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Mayck-E** [JoaoPedro110/Pet-Shop#1]
pegando meu código em...

**Comment by Mayck-E** [comment]
em que posso ajudar

**Comment by JoaoPedro110** [comment]
tabela sumiu

**Comment by JoaoPedro110** [comment]
<img width="431" alt="Captura de tela 2023-03-15 145600" src="https://user-images.githubusercontent.com/126287368/225400330-4205215a-445c-4a5d-89db-90846a96e523.png">

**Comment by Mayck-E** [comment]
vai no css e chama as tags da tabela separadas por virgula

**Comment by JoaoPedro110** [comment]
como companheiro

**Comment by JoaoPedro110** [comment]
utilizando o id?

**Comment by Mayck-E** [comment]
ñ, tipo
![image](https://user-images.githubusercontent.com/124847684/225400919-f58d3509-03e9-4a41-9c2f-ce996da1c8c1.png)

e usa border pra mecher no contorno da tabela

**Comment by JoaoPedro110** [comment]
ou vem aqui

**Comment by JoaoPedro110** [comment]
não entendi
